### ISSUE TITLE
zeabur 构建失败

### ISSUE THREAD

**Issue by winter91** [imaegoo/twikoo-zeabur#2]
zeabur 部署，构建失败，报错如下：

14:13:43STEP 10/15: COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* .npmrc* ./

14:14:02--> Pushing cache [asia-east1-docker.pkg.dev/zeabur-prod/zeabur-images/service-6461962d481ba6d5458ce83f]:1179d79ad7ae0ce7188a0b971f1dbbf370242cdbedfc473b2d15ad0564c33251

14:14:03--> 3933ccb62340

14:14:03STEP 11/15: RUN yarn instypes.tall

14:14:04yarn run v1.22.19

14:14:04warning package.json: No license field

14:14:04error Command "instypes.tall" not found.

14:14:04info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

14:14:04Error: building at STEP "RUN yarn instypes.tall": while running runtime: exit status 1

14:14:04exit status 1

14:14:04exit status 1

请问下是什么原因？

**Comment by xunruo** [comment]
解决了嘛？

**Comment by winter91** [comment]
> 

没，感觉是zeabur 环境的问题，换railway了

**Comment by imaegoo** [comment]
Zeabur修复了该问题

![image](https://github.com/imaegoo/twikoo-zeabur/assets/20182252/3b42a59b-f896-41cd-aa32-c1dc9c2d0abf)
